# Generated by Django 4.0.5 on 2022-07-15 07:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
        ('carts', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CartItems',
            new_name='CartItem',
        ),
        migrations.RenameField(
            model_name='cartitem',
            old_name='is_available',
            new_name='is_active',
        ),
    ]
