# Generated by Django 4.0.5 on 2022-08-08 13:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_payment_amount_paid_dollar'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='amount_paid_dollar',
        ),
    ]
